### ISSUE TITLE
友情提醒，已经被人做成马甲包了

### ISSUE THREAD

**Issue by qweqwqsqwwew** [CYBoys/Timi#12]
https://www.qimai.cn/app/baseinfo/appid/1350305497/country/cn

**Comment by LLLaiYoung** [comment]
非常感谢大佬的提醒 🤝


原始邮件
发件人:DavidHuangnotifications@github.com
收件人:CYBoys/TimiTimi@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年9月28日(周五) 17:00
主题:[CYBoys/Timi] 友情提醒，已经被人做成马甲包了 (#12)


https://www.qimai.cn/app/baseinfo/appid/1350305497/country/cn

**Comment by QQ53792889** [comment]
有可以做上面的那种类似的可以聊下5W左右看质量 zhaoshangjia AT outlook.com
