### ISSUE TITLE
Timi项目问题

### ISSUE THREAD

**Issue by Jay-Malei** [CYBoys/Timi#6]
有的文件缺失啊，项目运行不起来

**Comment by LLLaiYoung** [comment]
有截图么？在什么设备上？

**Comment by ConfusedWXW** [comment]
<img width="1280" alt="2017-12-18 9 00 09" src="https://user-images.githubusercontent.com/22948889/34107317-c3decf2a-e436-11e7-910f-41b8946e015f.png">
![Uploading 屏幕快照 2017-12-18 下午9.00.09.png…]()

**Comment by Jay-Malei** [comment]
<img width="274" alt="2017-12-18 9 05 46" src="https://user-images.githubusercontent.com/22948889/34107471-53c10e50-e437-11e7-90b2-c18a7104f050.png">
<img width="747" alt="2017-12-18 9 06 01" src="https://user-images.githubusercontent.com/22948889/34107473-555528f0-e437-11e7-8049-125fb3771a86.png">

**Comment by LLLaiYoung** [comment]
那几个文件本来都是没有的，pod install试试？

**Comment by Jay-Malei** [comment]
不行下下下来我就pod了
<img width="571" alt="2017-12-18 9 11 37" src="https://user-images.githubusercontent.com/22948889/34107680-22b479a4-e438-11e7-8672-ef7afdaefacf.png">

**Comment by Jay-Malei** [comment]
关注你很久了，之前老的项目可以运行！你更新后刚才去下下来运行了下就不行了

**Comment by LLLaiYoung** [comment]
谢谢！pod update 下就可以。

**Comment by Jay-Malei** [comment]
还在更新，应该可以！非常感谢！最近项目在用Masonry做动画，遇到坑，然后想到你的项目好像挺多动画效果的，下下来参考学习一下！
