### ISSUE TITLE
拉下来就报错

### ISSUE THREAD

**Issue by XaviorXiao** [CYBoys/Timi#7]
unable to read module map contents from 'Target Support Files/MMDrawerController/MMDrawerController.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “MMDrawerController.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/xavior/Downloads/Timi-master/Pods/Target Support Files/MMDrawerController/MMDrawerController.modulemap, NSUnderlyingError=0x7fe2c094a390 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by XaviorXiao** [comment]
编译报错

**Comment by BoySimonHu** [comment]
把Podfile.lock删了~重新install一下Pod，还不行就吧Podfile的版本删掉再install
