### ISSUE TITLE
Pod install 出现error

### ISSUE THREAD

**Issue by leesonli** [CYBoys/Timi#9]
当我使用Pod install时，出现error: No such file or directory - ~/Timi-master/Pods/Realm/Realm/Realm.modulemap.

我是一个新手想学习这个项目，但是不是特别会使用Pod相关的特性。
有没有一个截图步骤的文档指导我怎样打开使用这个项目？ （正常的iphone相关的开发都熟悉，Pod相关的不熟悉）

**Comment by LLLaiYoung** [comment]
把Podfile.lock 删掉之后，重新pod install 试试看呢
